### ISSUE TITLE
ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### ISSUE THREAD

**Issue by lddsb** [appleboy/drone-scp#105]
![image](https://user-images.githubusercontent.com/20765867/69020564-e27e8e80-09ef-11ea-8f0c-cd6d11229739.png)

> ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by lddsb** [comment]
sorry, it's my fault not drone-scp

**Comment by tubia** [comment]
Hey @lddsb I have the same problem. Could you explain how you solved this?

**Comment by lddsb** [comment]
> Hey @lddsb I have the same problem. Could you explain how you solved this?

The reason is that I changed the ssh port, please check your port

**Comment by tubia** [comment]
The port is correct for me. It is probably something related to the key generation I guess. I will add more as soon as I find more info on it.

**Comment by cavejay** [comment]
@tubia did you find anything?
