### ISSUE TITLE
unable to authenticate with password

### ISSUE THREAD

**Issue by amsdard** [appleboy/drone-scp#11]
Hi,

I'm trying to authenticate only with password, but it fails:

2016/12/07 11:14:23 scp file to remote server remote server.
2016/12/07 11:14:27 ssh: handshake failed: ssh: unable to authenticate, attempted methods [password none], no supported methods remain
ssh: handshake failed: ssh: unable to authenticate, attempted methods [password none], no supported methods remain

password/username is correct as I tested it with sftp client. Any idea what is wrong?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@amsdard authenticate with password is working for me. Please check your password again.
