### ISSUE TITLE
Support following symbolic links

### ISSUE THREAD

**Issue by bibekg** [appleboy/drone-scp#112]
I have a use case where some of the files I want to SCP over are symbolic links. Since this plugin uses the `tar` command to package up the source files before transferring, the symlinks stay symlinks when they reach the destination. However `tar` supports following symlinks by passing the `-h` option. Perhaps this plugin could add a Boolean parameter (`follow_symlink`) that supplies the `-h` option to `tar`. 

Or, a more generally useful although possibly dangerous solution might be to have a param that lets a consumer specify any options to `tar` they wish

**Comment by theonedemon** [comment]
up, any news?

**Comment by appleboy** [comment]
I will take it.
