### ISSUE TITLE
The win system uses commands that seem unable to be compressed into tar

### ISSUE THREAD

**Issue by bbhxwl** [appleboy/drone-scp#129]
win10
tar all files into C:\Users\47013\AppData\Local\Temp\927348223\RTpNoJYgNG.tar
tar: no files or directories specified
exit status 1

**Comment by GodDai** [comment]
linux
`Digest: sha256:143142ef73dcd3ce24c4c20b31cd6e2caf7456923ac431f7dce6932c8858b9e7
Status: Downloaded newer image for appleboy/drone-scp:latest
tar all files into /tmp/096136042/UgLqVwtDax.tar
tar: empty archive
exit status 1`

**Comment by appleboy** [comment]
Please enable the debug mode and post your command and all output log.

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/scp-action/pull/132
