### ISSUE TITLE
The path is incorrect.

### ISSUE THREAD

**Issue by bbhxwl** [appleboy/drone-scp#131]
I execute the following code to put all the files under /root/Web/ under /var/www/ , and I finally get /var/www /root/Web/

drone-scp --host **** --port 2222 --username ${{ secrets.SSH_USERNAME }} --password ${{ secrets.AIDELIPWD }} --target /var/www/ --source /root/web/

**Comment by geek-at** [comment]
having the same problems. So i either have to push from root (``source: ./``) but then it also pushes all of .git and the drone.yml itself, or push `source: web` and then have the folder "web" add on my target folder. Quite annoying

**Comment by lixh00** [comment]
I set `strip_components` to `1` and it works.
