### ISSUE TITLE
drone-scp error but file copy success

### ISSUE THREAD

**Issue by HighScore17** [appleboy/drone-scp#134]
in the Copy files to server sections, the files are copied successfully but with an error shown below

tar all files into /tmp/635380544/KwUcbibuAf.tar
scp file to server.
create folder C:\wamp64\www\siu
untar file KwUcbibuAf.tar
remove file KwUcbibuAf.tar
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file KwUcbibuAf.tar
20[22](https://github.com/organization/repo/runs/6296134220?check_suite_focus=true#step:4:22)/05/04 19:40:44 Process exited with status 1

**Comment by dsl-src** [comment]
Same error

**Comment by appleboy** [comment]
fixed in #132
