### ISSUE TITLE
Latest tag is arm64 only?

### ISSUE THREAD

**Issue by alexanderwink** [appleboy/drone-scp#147]
Pulling a new latest tag from Dockerhub I noticed that the latest tag is for arm64 arch only, To get the latest for amd64 I need to pull the linux-amd64 tag. I'm not sure is this was intended or in error but this will surely break a lot of existing pipelines running on amd64 that use the drone-scp plugin.

Personally I would prefer to have latest as a multi-arch build but I'm perfectly fine with using the tag linux-arm64 but then I think the latest tag should be removed completely.

Anyway, thank for maintaining this awesome plugin ❤️

**Comment by appleboy** [comment]
@alexanderwink The default latest tag is `linux-amd64` now. See the reference https://hub.docker.com/layers/appleboy/drone-scp/latest/images/sha256-ccdbb045fb26215023a5327f0db0a692e4fec5a72f6287837c15ca8fec714f50?context=explore

**Comment by alexanderwink** [comment]
So the change was intentional.
