### ISSUE TITLE
传输到目标主机的路径多了一层

### ISSUE THREAD

**Issue by hayye** [appleboy/drone-scp#162]
我想把本地的dist文件夹下的文件传输到服务器/home/project/charging/dist.new/目录下，但是实际上传输完成后，目标服务器路径变成了/home/project/charging/dist.new/dist/
这是我的配置文件：
`
  - name: deploy-test
    image: appleboy/drone-scp
    settings:
      host: 192.168.0.208
      username: root
      password:
        from_secret: ssh_test_password
      port: 22
      target: /home/project/charging/dist.new/
      source: ./dist/*
      overwrite: true
`

**Comment by appleboy** [comment]
```diff
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host: example.com
      target: /home/deploy/web
      source: dist/release.tar.gz
+     strip_components: 1
```
