### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by dashuaige2000** [appleboy/drone-scp#189]
drone-scp

error is connect: cannot assign requested address

host is a domain 

  - name: deploy
    pull: if-not-exists
    image: appleboy/drone-scp
    settings:
      host: nas.xxx.com
      username: xxxxx
      password: xxxxx
      port: 22
      target: /volume1/web/docs/
      source: ./docs/.vitepress/dist/*

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/drone-scp/pull/191

**Comment by appleboy** [comment]
try

```diff
  host: nas.xxx.com
  username: xxxxx
  password: xxxxx
  port: 22
+ protocol: tcp6
  target: /volume1/web/docs/
  source: ./docs/.vitepress/dist/*
```
