### ISSUE TITLE
Support wildcard string for source variable.

### ISSUE THREAD

**Issue by appleboy** [appleboy/drone-scp#31]
As title.

cc @asaf

**Comment by appleboy** [comment]
@asaf

Could you help try the wildcard list feature?

tag 1.3.0 https://hub.docker.com/r/appleboy/drone-scp/tags/

**Comment by asaf** [comment]
@appleboy yea, will report on this threat the results.

**Comment by asaf** [comment]
@appleboy works!

**Comment by appleboy** [comment]
@asaf Thanks for your confirmation.
