### ISSUE TITLE
Switch glide to govendor

### ISSUE THREAD

**Issue by appleboy** [appleboy/drone-scp#33]
https://github.com/kardianos/govendor

**Comment by asaf** [comment]
@appleboy just from curiosity, why switching glide to govendor?

**Comment by appleboy** [comment]
@asaf `glide` can't update `gopkg.in` package automatically. I want to update a package `drone-scp` used but glide will update all dependency package.

**Comment by appleboy** [comment]
@asaf I will try the google vendor tool https://github.com/golang/dep

**Comment by asaf** [comment]
@appleboy really? they mentioned it's fully supported, I didn't know.
I also find it odd committing any external dependencies (the `vendor` folder) into the repo,
and yes, golang/dep looks promising, worth a try :-)
