### ISSUE TITLE
Support drone ci secret method

### ISSUE THREAD

**Issue by Blackrose** [appleboy/drone-scp#75]
Hi, i use drone-scp with drone to auto build my task.And I follow the document(http://plugins.drone.io/appleboy/drone-scp/) to setting username and password is work fine in drone.yml file.But i doesn't want write plaintext the username and password in that file.Did the drone-scp support secret method of drone?Thanks

**Comment by vishal24tuniki** [comment]
@Blackrose It supports all these secrets, you don't need plain texts https://github.com/appleboy/drone-scp/blob/master/main.go#L29

**Comment by Blackrose** [comment]
Thanks.I will try it.
