### ISSUE TITLE
Error doesn't trigger build failure (Drone 1.0.0-rc6)

### ISSUE THREAD

**Issue by zdk123** [appleboy/drone-scp#93]
For example, providing an incorrect key doesn't trigger failure of the drone step:
![image](https://user-images.githubusercontent.com/2637124/53979246-4455cd00-40db-11e9-8de6-156b3893683b.png)

We shouldn't be getting a green checkmark here. Does this replicate on another system?

**Comment by appleboy** [comment]
@zdk123 I will take it.

**Comment by appleboy** [comment]
@zdk123 Please try the latest version.

**Comment by zdk123** [comment]
working now, thanks!
![image](https://user-images.githubusercontent.com/2637124/54158266-7d19dd00-4420-11e9-8310-3c7eb26273ef.png)
