### ISSUE TITLE
Untar not working

### ISSUE THREAD

**Issue by Maicus** [appleboy/drone-scp#95]
Hey I have a problem I want to deploy a file to a remote machine running RancherOS (it only has busybox running on it)

I can login, but after that it tries to untar and exits with status code 1.
```
docker run --rm \
-e PLUGIN_HOST=master \
-e PLUGIN_KEY_PATH=key \
-e PLUGIN_USERNAME=rancher \
-e PLUGIN_TARGET=/ \
-e PLUGIN_SOURCE=/home/ubuntu/ \
-e PLUGIN_DEBUG=true \
-v $(pwd):$(pwd) \
-w $(pwd) \
appleboy/drone-scp
```
Output:
```
tar all files into /tmp/956253892/394yg2ESuA.tar
$ tar -cf /tmp/956253892/394yg2ESuA.tar /home/ubuntu/
tar: removing leading '/' from member names
scp file to server.
create folder /
untar file 394yg2ESuA.tar
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file 394yg2ESuA.tar
2019/03/21 11:30:36 Process exited with status 1
```

Do you have any idea?

**Comment by appleboy** [comment]
Try the latest version.

**Comment by bluemwhitew** [comment]
Also having this issue after checking several solutions. Configuration [can be found here](https://www.github.com/bluemwhitew/blackpool-bible-tattoo-4-u.biz/blob/master/.github/workflows/deploy.yaml). 😕
